# EXAMPLE
version: '3'
services:
  web:
    build: .
    image: remote-repo/image:tag # For local tag easy to push
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - redis
  redis:
    image: redis
volumes:
  logvolume01: {}